In [1]:
import pandas as pd 
import numpy as np

In [9]:
df = pd.read_csv("C:\\Users\\raush\\OneDrive\\Desktop\\All Project\\postings.csv")

In [10]:
df.shape

(123849, 31)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB

In [13]:
# First 60000 rows
df.iloc[:60000].to_csv("part1.csv", index=False)

# Remaining rows
df.iloc[60000:].to_csv("part2.csv", index=False)

In [14]:
df.dtypes

job_id                          int64
company_name                   object
title                          object
description                    object
max_salary                    float64
pay_period                     object
location                       object
company_id                    float64
views                         float64
med_salary                    float64
min_salary                    float64
formatted_work_type            object
applies                       float64
original_listed_time          float64
remote_allowed                float64
job_posting_url                object
application_url                object
application_type               object
expiry                        float64
closed_time                   float64
formatted_experience_level     object
skills_desc                    object
listed_time                   float64
posting_domain                 object
sponsored                       int64
work_type                      object
currency                       object
compensation_type              object
normalized_salary             float64
zip_code                      float64
fips                          float64
dtype: object

In [15]:
df.head(5)

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [16]:
df.tail(5)

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,NaN,1.713572e+12,www.pinterestcareers.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,NaN,1.713572e+12,epsoperations.bamboohr.com,0,FULL_TIME,NaN,NaN,NaN,99201.0,53063.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [17]:
df.isnull().sum()

job_id                             0
company_name                    1719
title                              0
description                        7
max_salary                     94056
pay_period                     87776
location                           0
company_id                      1717
views                           1689
med_salary                    117569
min_salary                     94056
formatted_work_type                0
applies                       100529
original_listed_time               0
remote_allowed                108603
job_posting_url                    0
application_url                36665
application_type                   0
expiry                             0
closed_time                   122776
formatted_experience_level     29409
skills_desc                   121410
listed_time                        0
posting_domain                 39968
sponsored                          0
work_type                          0
currency                       87776
compensation_type              87776
normalized_salary              87776
zip_code                       20872
fips                           27415
dtype: int64

In [21]:
df = df.dropna(subset=['company_name'])
print("After:", df.shape )

After: (122130, 31)

In [22]:
df = df.dropna(subset=['max_salary'])
print("After:",df.shape)

After: (29338, 31)

In [24]:
df.shape

(29338, 31)

In [25]:
df['company_name'].isnull().sum()

np.int64(0)

In [26]:
df['max_salary'].isnull().sum()

np.int64(0)

In [27]:
df.shape

(29338, 31)

In [28]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.to_csv("clean_postings.csv", index=False)

In [32]:
import os
os.listdir()

['.anaconda',
 '.android',
 '.aws',
 '.bash_history',
 '.cache',
 '.conda',
 '.condarc',
 '.continuum',
 '.cursor',
 '.eclipse',
 '.gitconfig',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.Ld9VirtualBox',
 '.m2',
 '.matplotlib',
 '.p2',
 '.python_history',
 '.redhat',
 '.ssh',
 '.trae',
 '.trae-aicc',
 '.VirtualBox',
 '.virtual_documents',
 '.vscode',
 '7168.f5129f48620a03126642.css',
 'anaconda3',
 'api.js.download',
 'app.css',
 'app.js.download',
 'AppData',
 'Application Data',
 'beecoder_website',
 'bundle.js.download',
 'cb=gapi.loaded_0',
 'clean_postings.csv',
 'client',
 'configuration-Office2019Enterprise.xml',
 'configuration-Office2021Enterprise.xml',
 'configuration-Office365-x64.xml',
 'configuration-Office365-x86.xml',
 'Contacts',
 'Cookies',
 'css',
 'css2',
 'css2(1)',
 'daaa.py',
 'dd_jdbc_suite_console_install.log',
 'Documents',
 'Downloads',
 'eclipse',
 'eclipse-workspace',
 'Favorites',
 'IdeaSnapshots',
 'index.css',
 'inst.ini',
 'InstallAnywhere',
 'Intelipant .ipynb',
 'job posting.ipynb',
 'js',
 'jupyterlab-index-6e625d63b639a89a2504.html',
 'jupyterlabinjected.698dd07773af0f785a6a.css',
 'jupyterlabinjected.efecb9bd94db2d27100d.js.download',
 'KernelEditor.56ec1322d855ad0f5482.css',
 'Links',
 'Local Settings',
 'logo-64x64.png',
 'marksheet .jpg',
 'MathJax.js.download',
 'Matplolib.ipynb',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{3f133865-d48d-11ef-96f8-a88ddf0e2c2b}.TM.blf',
 'NTUSER.DAT{3f133865-d48d-11ef-96f8-a88ddf0e2c2b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{3f133865-d48d-11ef-96f8-a88ddf0e2c2b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'numpy.ipynb',
 'nuuid.ini',
 'OneDrive',
 'os manual .c',
 'os manual .java',
 'os manual .py',
 'os manual .scss',
 'pandas.ipynb',
 'part1.csv',
 'part2.csv',
 'PrintHood',
 'project .ipynb',
 'Python.ipynb',
 'raushan.ipynb',
 'Raushan.py',
 'Recent',
 'remoteEntry.4fc7f7fa3fcdc834e48b.js.download',
 'remoteEntry.5586bbdee77c5d90dd3c.js.download',
 'remoteEntry.5cbb9d2323598fbda535.js.download',
 'rk',
 'rk.java',
 'runtime.8483da0856ddae2e20c3.js.download',
 'runtime.js.download',
 'Saved Games',
 'Searches',
 'selesta2k24',
 'SendTo',
 'setup.exe',
 'site-logo.svg',
 'source',
 'Start Menu',
 'Templates',
 'This PC - Shortcut.lnk',
 'Untitled Folder',
 'Untitled.ipynb',
 'untitled.py',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'useruid.ini',
 'vendor.904b07b1243165f67bd7.js.download',
 'vendor.js.download',
 'Videos',
 'vmlogs',
 'wekafiles',
 'winemag-data-130k-v2.csv',
 'WPS Cloud Files']

In [33]:
df.isnull().sum()

job_id                            0
company_name                      0
title                             0
description                       1
max_salary                        0
pay_period                        0
location                          0
company_id                        0
views                           424
med_salary                    29338
min_salary                        0
formatted_work_type               0
applies                       21589
original_listed_time              0
remote_allowed                25117
job_posting_url                   0
application_url               11644
application_type                  0
expiry                            0
closed_time                   29207
formatted_experience_level     6336
skills_desc                   29137
listed_time                       0
posting_domain                13078
sponsored                         0
work_type                         0
currency                          0
compensation_type                 0
normalized_salary                 0
zip_code                       5891
fips                           7377
dtype: int64